### ISSUE TITLE
Local compiling for web failed with latest Flutter version

### ISSUE THREAD

**Issue by torbenkeller** [rxlabz/panache#32]
Because the linked website is unusable because of errors i wanted to run the project locally and got this compiler error when I tried: 
```
flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...

Compiler message:
../panache_ui/lib/src/screens/editor/controls/color_picker/color_slider.dart:1101:9: Error: The superclass,
'Diagnosticable', has no unnamed constructor that takes no arguments.
  const GradientSliderThemeData({
        ^^^^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ProgramCompiler._emitSuperConstructorCallIfNeeded (package:dev_compiler/src/kernel/compiler.dart:1465:14)
#2      ProgramCompiler._emitConstructorBody (package:dev_compiler/src/kernel/compiler.dart:1419:19)
#3      ProgramCompiler._emitConstructor.<anonymous closure>.<anonymous closure>
(package:dev_compiler/src/kernel/compiler.dart:1375:19)
#4      ProgramCompiler._superDisallowed (package:dev_compiler/src/kernel/compiler.dart:3125:24)
#5      ProgramCompiler._emitConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1374:15)
#6      ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2116:25)
#7      ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3115:18)
#8      ProgramCompiler._emitConstructor (package:dev_compiler/src/kernel/compiler.dart:1372:16)
#9      ProgramCompiler._defineConstructors (package:dev_compiler/src/kernel/compiler.dart:972:38)
#10     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:567:19)
#11     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:510:21)
#12     List.forEach (dart:core-patch/growable_array.dart:282:8)
#13     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:459:23)
#14     List.forEach (dart:core-patch/growable_array.dart:282:8)
#15     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:345:15)
#16     JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:131:33)
<asynchronous suspension>
#17     FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:616:20)
<asynchronous suspension>
#18     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:523:15)
<asynchronous suspension>
#19     _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:40:22)
#20     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1154:26)
#21     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#27     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#37     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#38     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#39     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#40     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#42     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#46     _StreamController._add (dart:async/stream_controller.dart:655:7)
#47     _StreamController.add (dart:async/stream_controller.dart:597:5)
#48     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#49     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#53     _StreamController._add (dart:async/stream_controller.dart:655:7)
#54     _StreamController.add (dart:async/stream_controller.dart:597:5)
#55     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
#56     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
#57     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#59     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
the Dart compiler exited unexpectedly.
Syncing files to device Chrome...                               13.161ms (!)
Failed to compile application.
```

Flutter Doctor:
```
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.17763.1098], locale de-DE)
    • Flutter version 1.17.0 at C:\src\flutter
    • Framework revision d3ed9ec945 (12 hours ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Torben\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (3 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome              • chrome        • web-javascript • Google Chrome 80.0.3987.163
    • Web Server          • web-server    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by torbenkeller** [comment]
There is a pull request for this
